version: '2'
services:
  mysql:
    image: lvo9/mysql
    container_name: mysql
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-flags:/flags
      - ./mysql/init.sql:/init.sql
    environment:
      - TZ=Europe/Paris
      - MYSQL_USER=root
      - STARTUP_SQL=/init.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    links:
      - mysql:db
  apache:
    build: docker_apache
    container_name: apache
    restart: always
    ports:
      - 80:80
    links:
      - mysql
    volumes:
      - ./html-sources:/app
      - ./docker_apache/apache2.conf:/etc/apache2/apache2.conf
      - ./docker_apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker_apache/apache-php.ini:/etc/php5/apache2/php.ini
      - ./docker_apache/cli-php.ini:/etc/php5/cli/php.ini
      - ./docker_apache/apache-20-xdebug.ini:/etc/php5/apache2/conf.d/20-xdebug.ini
      - ./docker_apache/cli-20-xdebug.ini:/etc/php5/cli/conf.d/20-xdebug.ini
      - ./docker_apache/refresh-acl.sh:/refresh-acl.sh
      - ./docker_apache/run.sh:/run.sh
volumes:
  mysql-data: ~
  mysql-flags: ~
